"""
    smarteeth

    One of the apps of the IoT-dataset  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import smarteeth
from smarteeth.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_brushing_conditions_check_get(self):
        """Test case for brushing_conditions_check_get

        """
        pass

    def test_brushing_conditions_humidity_humidity_value_post(self):
        """Test case for brushing_conditions_humidity_humidity_value_post

        """
        pass

    def test_brushing_conditions_temperature_temperature_value_post(self):
        """Test case for brushing_conditions_temperature_temperature_value_post

        """
        pass

    def test_brushing_conditions_toothpaste_weight_amount_post(self):
        """Test case for brushing_conditions_toothpaste_weight_amount_post

        """
        pass

    def test_brushing_direction_get(self):
        """Test case for brushing_direction_get

        """
        pass

    def test_brushing_move_post(self):
        """Test case for brushing_move_post

        """
        pass

    def test_brushing_start_username_post(self):
        """Test case for brushing_start_username_post

        """
        pass

    def test_brushing_time_get(self):
        """Test case for brushing_time_get

        """
        pass

    def test_configuration_username_get(self):
        """Test case for configuration_username_get

        """
        pass

    def test_configuration_username_post(self):
        """Test case for configuration_username_post

        """
        pass

    def test_health_gum_bleeding_get(self):
        """Test case for health_gum_bleeding_get

        """
        pass

    def test_health_tartrum_get(self):
        """Test case for health_tartrum_get

        """
        pass

    def test_health_tooth_color_tooth_color_value_post(self):
        """Test case for health_tooth_color_tooth_color_value_post

        """
        pass

    def test_statistics_username_get(self):
        """Test case for statistics_username_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
