# flake8: noqa

"""
    WindWow

    One of the apps of the IoT-dataset  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from windwow_api_client.api_client import ApiClient

# import Configuration
from windwow_api_client.configuration import Configuration

# import exceptions
from windwow_api_client.exceptions import OpenApiException
from windwow_api_client.exceptions import ApiAttributeError
from windwow_api_client.exceptions import ApiTypeError
from windwow_api_client.exceptions import ApiValueError
from windwow_api_client.exceptions import ApiKeyError
from windwow_api_client.exceptions import ApiException
