"""
    FlowerPower

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flowerpower
from flowerpower.model.setting_name import SettingName


class TestSettingName(unittest.TestCase):
    """SettingName unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSettingName(self):
        """Test SettingName"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SettingName()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
