# flake8: noqa

"""
    smarteeth

    One of the apps of the IoT-dataset  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from smarteeth.api_client import ApiClient

# import Configuration
from smarteeth.configuration import Configuration

# import exceptions
from smarteeth.exceptions import OpenApiException
from smarteeth.exceptions import ApiAttributeError
from smarteeth.exceptions import ApiTypeError
from smarteeth.exceptions import ApiValueError
from smarteeth.exceptions import ApiKeyError
from smarteeth.exceptions import ApiException
