"""
    FlowerPower

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_activate_solar_lamp_get(self):
        """Test case for activate_solar_lamp_get

        """
        pass

    def test_inject_minerals_get(self):
        """Test case for inject_minerals_get

        """
        pass

    def test_irrigate_soil_get(self):
        """Test case for irrigate_soil_get

        """
        pass

    def test_plant_info_put(self):
        """Test case for plant_info_put

        Updates plant settings.  # noqa: E501
        """
        pass

    def test_settings_put(self):
        """Test case for settings_put

        Updates all settings by the specified JSON.  # noqa: E501
        """
        pass

    def test_settings_setting_name_get(self):
        """Test case for settings_setting_name_get

        Gets the value of the specified setting.  # noqa: E501
        """
        pass

    def test_settings_setting_name_setting_value_put(self):
        """Test case for settings_setting_name_setting_value_put

        Sets a value to a setting specified by name.  # noqa: E501
        """
        pass

    def test_shovel_get(self):
        """Test case for shovel_get

        Shovels the soil.  # noqa: E501
        """
        pass

    def test_soil_status_get(self):
        """Test case for soil_status_get

        """
        pass

    def test_status_get(self):
        """Test case for status_get

        Return plant status from local file.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
