"""
    WindWow

    One of the apps of the IoT-dataset  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import windwow
from windwow.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_settings_setting_name_get(self):
        """Test case for settings_setting_name_get

        """
        pass

    def test_settings_setting_name_setting_value_post(self):
        """Test case for settings_setting_name_setting_value_post

        """
        pass

    def test_user_settings_post(self):
        """Test case for user_settings_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
