"""
    SmartKettle

    One app of the IoT-dataset  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import smartkettle
from smartkettle.model.make_tea_temperature import MakeTeaTemperature
globals()['MakeTeaTemperature'] = MakeTeaTemperature
from smartkettle.model.inline_object import InlineObject


class TestInlineObject(unittest.TestCase):
    """InlineObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineObject(self):
        """Test InlineObject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineObject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
