"""
    SmartKettle

    App that controls an smart electric kettle. Part of the IoT-dataset for fuzzing Smart Home Appliances.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import smartkettle
from smartkettle.model.make_tea_temperature import MakeTeaTemperature


class TestMakeTeaTemperature(unittest.TestCase):
    """MakeTeaTemperature unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMakeTeaTemperature(self):
        """Test MakeTeaTemperature"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MakeTeaTemperature()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
