# flake8: noqa

"""
    SmartKettle

    App that controls an smart electric kettle. Part of the IoT-dataset for fuzzing Smart Home Appliances.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from smartkettle.api_client import ApiClient

# import Configuration
from smartkettle.configuration import Configuration

# import exceptions
from smartkettle.exceptions import OpenApiException
from smartkettle.exceptions import ApiAttributeError
from smartkettle.exceptions import ApiTypeError
from smartkettle.exceptions import ApiValueError
from smartkettle.exceptions import ApiKeyError
from smartkettle.exceptions import ApiException
